name=easy_stack
version=1.1.2
author=gooderfreed <gooderfreed@gmail.com>
maintainer=gooderfreed <gooderfreed@gmail.com>
sentence=An absurdly fast, header-only, and safe LIFO stack allocator.
paragraph=A platform-agnostic stack allocator utilizing an inverted bi-directional buffer layout with dynamic metadata scaling to achieve zero alignment padding waste and O(1) speeds.
category=Data Storage
url=https://github.com/easymem/easy_stack
architectures=*